### ISSUE TITLE
UI thread performance improved but the Raster thread performance is significantly decreased

### ISSUE THREAD

**Issue by Hwan-seok** [ASGAlex/flame_tiled_utils#2] opened 2022-09-23 04:53 UTC
I tested this package on my map because most of my maps are very big.
In the beginning, I am very excited because the execution time of render() and update() is significantly decreased.
But after some performance testing, I found it drops the FPS from 60 to 20. 
So I tested through performance view and found something that the UI thread time is decreased but Raster thread time is more increased than the former one.

### As usual

https://user-images.githubusercontent.com/38072762/191893936-988f5181-1db3-4dde-b0a6-0c0e38df09c2.mov

![스크린샷 2022-09-23 오후 1 35 48](https://user-images.githubusercontent.com/38072762/191892992-71d980fe-0b33-4e19-a07f-fcffcef9d922.png)

### Using this package

https://user-images.githubusercontent.com/38072762/191893930-081be481-a284-4308-8ee7-a7c8ce88734e.mov

### FYI,
- My map size is 100 x 100 and split into two components in the middle of the layer.
- Used only ImageBatchCompiler.compileMapLayer
```dart

  final mapComponent = TiledComponent(renderableTiledMap);

  final imageCompiler = ImageBatchCompiler();
  final layerIdx =
      mapComponent.tileMap.map.layers.indexWhere((element) => element.name == 'some middle layer');
  final belowLayerNames =
      mapComponent.tileMap.map.layers.sublist(0, layerIdx).map((e) => e.name).toList();
  final aboveLayerNames =
      mapComponent.tileMap.map.layers.sublist(layerIdx).map((e) => e.name).toList();
  final mapUnderPlayer = await imageCompiler.compileMapLayer(
    tileMap: mapComponent.tileMap,
    layerNames: belowLayerNames,
  );
  mapUnderPlayer.priority = GamePriority.MAP_UNDER_PLAYER;
  final mapAbovePlayer = await imageCompiler.compileMapLayer(
    tileMap: mapComponent.tileMap,
    layerNames: aboveLayerNames,
  );
  mapAbovePlayer.priority = GamePriority.MAP_ABOVE_PLAYER;
```
---
Am I doing something wrong? or is it natural behavior?

**Comment by ASGAlex** [comment] 2022-09-24 23:39
I'm afraid there is no way to change anything here. Yes, everything is ok in your example.

Layers compilation simple creates new Image from tiled map, it saves your update()  time by forcing system to render one big image inside position component.

You can achieve same behavior trying to save your map's layers into Image and then to render it through SpriteComponent. Would it work fast on your machine or you would face same problem with raster layer?

**Comment by Hwan-seok** [comment] 2022-09-25 14:24
Thanks for the answer
Does this issue only apply to specific maps? Is yours OK with this?

**Comment by ASGAlex** [comment] 2022-09-26 16:23
I think there could not to be any special related to map format. Every map ends up as Image or group of Images wrapped to PositionComponent(s). Technically it is like if you would use SpriteComponent directly,

Anyway you cause is interecting.  May be you hardware can't to work with big images but would be faster if images would be split into smaller parts. It is a point to experiment with.

**Comment by ASGAlex** [comment] 2023-01-19 16:48
I am going to close this issue becouse it is impossible to fix it with current library's architecture. It is "corrupted by design". I'd recomment to try it's successor instead,  https://github.com/ASGAlex/flame_spatial_grid. It provides the same features for tiles processing, but without generating an extra-large images.

**Closed by ASGAlex** 2023-01-19 16:48 UTC
